### ISSUE TITLE
Update github pages deployment

### ISSUE THREAD

**Issue by jpbnetley** [jpbnetley/joke-of-the-day#150]
[source](https://github.com/JamesIves/github-pages-deploy-action)
```yml         
- name: Deploy
  uses: JamesIves/github-pages-deploy-action@v4
  with:
    branch: gh-pages
    folder: storybook-build
```
